apiVersion: apps/v1
kind: Deployment
metadata:
  name: toho-vote-be
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: toho-vote-be
          env:
            - name: NACOS_NAMESPACE
              value: "prod"
